language: node_js
node_js:
  - '16.10.0'
branches:
  only:
    - main
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - yarn && GIT_USER="${GH_NAME}" DEPLOYMENT_BRANCH=${DEPLOYMENT_BRANCH} yarn deploy